repos:
-   repo: https://github.com/PyCQA/docformatter.git
    rev: v1.5.1
    hooks:
    -   id: docformatter
-   repo: https://github.com/hadialqattan/pycln.git
    rev: v2.1.3
    hooks:
    -   id: pycln
-   repo: https://github.com/PyCQA/flake8.git
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/pylint.git
    rev: v2.16.0b0
    hooks:
    -   id : pylint
        args: [--ignored-modules=yaml]
-   repo: https://github.com/charliermarsh/ruff-pre-commit.git
    rev: v0.0.236
    hooks:
    -   id: ruff
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v0.991
    hooks:
    -   id: mypy
        additional_dependencies: [types-PyYAML==6.0.12.3]
-   repo: https://github.com/PyCQA/bandit.git
    rev: 1.7.4
    hooks:
    -   id: bandit

